from typing import Any, Tuple, Union

# Context and Setup
def CreateContext(name: str) -> Any: ...
def DestroyContext(ctx: Any) -> None: ...
def Attach(ctx: Any, font: Any) -> None: ...
def GetBuiltinFont() -> Any: ...

# Condition and flags
def Cond_FirstUseEver() -> int: ...
def ChildFlags_None() -> int: ...

# Window and drawing
def SetNextWindowPos(ctx: Any, x: float, y: float, cond: int = ...) -> None: ...
def SetNextWindowSize(ctx: Any, w: float, h: float, cond: int = ...) -> None: ...
def SetNextWindowSizeConstraints(ctx: Any, min_w: float, min_h: float, max_w: float, max_h: float) -> None: ...
def Begin(ctx: Any, name: str, p_open: Union[bool, None] = ..., flags: int = ...) -> Tuple[bool, bool]: ...
def End(ctx: Any) -> None: ...
def Separator(ctx: Any) -> None: ...
def Text(ctx: Any, text: str) -> None: ...
def TextWrapped(ctx: Any, text: str) -> None: ...
def SameLine(ctx: Any) -> None: ...
def TextColored(ctx: Any, color: int, text: str) -> None: ...
def GetContentRegionAvail(ctx: Any) -> Tuple[float, float]: ...
def GetCursorPosX(ctx: Any) -> float: ...
def SetCursorPosX(ctx: Any, x: float) -> None: ...
def Checkbox(ctx: Any, label: str, active: bool) -> Tuple[bool, bool]: ...
def BeginChild(ctx: Any, str_id: str, size_x: float = ..., size_y: float = ..., child_flags: int = ..., window_flags: int = ...) -> bool: ...
def EndChild(ctx: Any) -> None: ...
def SetScrollHereY(ctx: Any, center_y_ratio: float = ...) -> None: ...
def Spacing(ctx: Any) -> None: ...
def InputText(ctx: Any, label: str, buf: str, flags: int = ...) -> Tuple[bool, str]: ...
def InputTextFlags_EnterReturnsTrue() -> int: ...
def Button(ctx: Any, label: str, size_x: float = ..., size_y: float = ...) -> bool: ...
def SetNextItemWidth(ctx: Any, width: float) -> None: ...

# Colors & Vars
def Col_WindowBg() -> int: ...
def Col_ChildBg() -> int: ...
def Col_PopupBg() -> int: ...
def Col_Text() -> int: ...
def Col_TextDisabled() -> int: ...
def Col_TitleBg() -> int: ...
def Col_TitleBgActive() -> int: ...
def Col_TitleBgCollapsed() -> int: ...
def Col_Border() -> int: ...
def Col_BorderShadow() -> int: ...
def Col_Button() -> int: ...
def Col_ButtonHovered() -> int: ...
def Col_ButtonActive() -> int: ...
def Col_FrameBg() -> int: ...
def Col_FrameBgHovered() -> int: ...
def Col_FrameBgActive() -> int: ...
def Col_ScrollbarBg() -> int: ...
def Col_ScrollbarGrab() -> int: ...
def Col_ScrollbarGrabHovered() -> int: ...
def Col_ScrollbarGrabActive() -> int: ...
def Col_Separator() -> int: ...
def Col_CheckMark() -> int: ...

def StyleVar_WindowRounding() -> int: ...
def StyleVar_ChildRounding() -> int: ...
def StyleVar_FrameRounding() -> int: ...
def StyleVar_GrabRounding() -> int: ...
def StyleVar_ScrollbarRounding() -> int: ...
def StyleVar_WindowPadding() -> int: ...
def StyleVar_FramePadding() -> int: ...
def StyleVar_ItemSpacing() -> int: ...
def StyleVar_ScrollbarSize() -> int: ...

def PushStyleColor(ctx: Any, idx: int, col: int) -> None: ...
def PushStyleVar(ctx: Any, idx: int, val1: float, val2: float = ...) -> None: ...
def PopStyleColor(ctx: Any, count: int = ...) -> None: ...
def PopStyleVar(ctx: Any, count: int = ...) -> None: ...
