from typing import Any, Tuple

def RPR_defer(func_name: str) -> None: ...
def RPR_ShowConsoleMsg(msg: str) -> None: ...
def RPR_CountSelectedTracks(proj: Any) -> int: ...
def RPR_GetSelectedTrack(proj: Any, idx: int) -> Any: ...
def RPR_GetSetMediaTrackInfo_String(track: Any, parm: str, stringNeed: str, setNew: bool) -> Tuple[bool, Any, str, str, bool]: ...
def RPR_GetMediaTrackInfo_Value(track: Any, parm: str) -> float: ...
def RPR_GetNumTracks() -> int: ...
def RPR_GetProjectTimeSignature2(proj: Any, bpmOut: float, bpiOut: int) -> Tuple[bool, float, float, int]: ...
def RPR_GetAudioDeviceInfo(key: str, descOut: str, descOut_sz: int) -> Tuple[bool, str, str, int]: ...
def RPR_GetProjectPath(szOut: str, szOut_sz: int) -> Tuple[bool, str, int]: ...
def RPR_CountTrackMediaItems(track: Any) -> int: ...
def RPR_GetTrackColor(track: Any) -> int: ...
def RPR_TrackFX_GetCount(track: Any) -> int: ...
def RPR_TrackFX_GetFXName(track: Any, fx: int, bufOut: str, bufOut_sz: int) -> Tuple[bool, Any, int, str, int]: ...
def RPR_TrackFX_GetNumParams(track: Any, fx: int) -> int: ...
def RPR_TrackFX_GetParamName(track: Any, fx: int, param: int, bufOut: str, bufOut_sz: int) -> Tuple[bool, Any, int, int, str, int]: ...
def RPR_TrackFX_GetParam(track: Any, fx: int, param: int, minvalOut: float, maxvalOut: float) -> Tuple[float, float, float]: ...
def RPR_TrackFX_GetEnabled(track: Any, fx: int) -> bool: ...
def RPR_Main_OnCommand(command: int, flag: int) -> None: ...
def RPR_GetTimeSelection(startOut: float, endOut: float, lenOut: float, isInLoopOut: bool) -> Tuple[float, float, float, bool]: ...
def RPR_GetOutputLatency() -> float: ...
def RPR_CSurf_OnRecord() -> None: ...
def RPR_GetSetProjectInfo_String(proj: Any, parm: str, stringNeed: str, setNew: bool) -> Tuple[bool, int, str, str, bool]: ...
def RPR_GetAppVersion() -> str: ...
