"""
ReaBot DSP - Analyzer Orchestrator

Loads audio files and runs all DSP modules based on AnalysisFlags
generated by the keyword router (or passed manually for Phase 6 override).
"""

import librosa
import numpy as np
import logging
from typing import Dict, Any

from .types import AnalysisFlags
from .router import route_analysis
from .spectrum import analyze_spectrum
from .dynamics import analyze_dynamics
from .muddiness import analyze_tonal_balance
from .transients import analyze_transients
from .musical import analyze_musicality
from .stereo import analyze_stereo

logger = logging.getLogger("reabot.dsp")

# Target sample rate for consistent FFT bin sizes across all files
TARGET_SR = 44100
# Maximum duration to analyze (to prevent OOM on full 10-minute stems)
MAX_DURATION_SEC = 30.0


async def analyze_audio_file(
    wav_path: str,
    user_question: str = "",
    stereo: bool = False,
    flags: AnalysisFlags | None = None,
) -> Dict[str, Any]:
    """
    Main entry point for DSP analysis of a single audio file.

    Args:
        wav_path: Absolute path to the WAV file.
        user_question: The user's question or prompt. Used by the keyword
            router to determine which modules to run if flags is None.
        stereo: If True, load audio as stereo and run stereo analysis module.
            This must be set BEFORE routing because it changes how audio is loaded.
        flags: Pre-built AnalysisFlags. If None, flags are auto-generated
            from user_question via the keyword router.

    Returns:
        A combined dictionary of all analysis results.
    """
    logger.info("Starting DSP analysis for %s (stereo=%s)", wav_path, stereo)

    # Determine which modules to run
    if flags is None:
        flags = route_analysis(user_question)
        logger.debug("Router flags from prompt: %s", flags)

    try:
        # Load audio — stereo determines mono vs stereo loading
        if stereo:
            y_raw, sr_raw = librosa.load(
                wav_path,
                sr=TARGET_SR,
                mono=False,  # preserve stereo channels
                duration=MAX_DURATION_SEC,
            )
            sr = int(sr_raw)
            # Ensure we actually got a stereo file
            if y_raw.ndim == 1:
                # File was mono despite request — treat as mono
                logger.warning("Stereo requested but file %s is mono. Proceeding as mono.", wav_path)
                y_mono = y_raw
                y_stereo = None
            else:
                # Downmix to mono for all non-stereo modules
                y_mono = (y_raw[0] + y_raw[1]) / 2.0
                y_stereo = y_raw
        else:
            y_mono, sr_raw = librosa.load(
                wav_path,
                sr=TARGET_SR,
                mono=True,
                duration=MAX_DURATION_SEC,
            )
            sr = int(sr_raw)
            y_stereo = None

        if len(y_mono) == 0:
            raise ValueError(f"Audio file is empty or unreadable: {wav_path}")

        combined: Dict[str, Any] = {}

        # Run each module only if its flag is set
        if flags.run_spectrum:
            spectrum_results = analyze_spectrum(y_mono, sr)
            combined.update(spectrum_results)

        if flags.run_dynamics:
            combined.update(analyze_dynamics(y_mono))

        if flags.run_muddiness:
            # muddiness.py reads from spectrum results — ensure spectrum was run
            if flags.run_spectrum and "band_energy" in combined:
                combined["tonal_balance"] = analyze_tonal_balance(combined)
            else:
                # Spectrum wasn't run but muddiness was requested — run spectrum now
                spectrum_for_muddiness = analyze_spectrum(y_mono, sr)
                combined["tonal_balance"] = analyze_tonal_balance(spectrum_for_muddiness)

        if flags.run_transients:
            combined["transients"] = analyze_transients(y_mono, sr)

        if flags.run_musical:
            combined["musical"] = analyze_musicality(y_mono, sr)

        # Stereo analysis — only if explicitly requested and file is stereo
        if stereo and y_stereo is not None:
            combined["stereo"] = analyze_stereo(y_stereo, sr)

        logger.info("Analysis complete for %s", wav_path)
        return combined

    except Exception as e:
        logger.error("DSP analysis failed for %s: %s", wav_path, str(e))
        raise
