"""
ReaSig DSP - Analyzer Orchestrator

Loads audio files and runs all DSP modules based on AnalysisFlags
generated by the keyword router (or passed manually for Phase 6 override).

This is a SYNCHRONOUS function. The async server wraps it in
asyncio.to_thread() (Phase C) to avoid blocking the event loop.
"""

import librosa
import numpy as np
import logging
from typing import Dict, Any

from .types import AnalysisFlags
from .router import route_analysis
from .spectrum import analyze_spectrum
from .dynamics import analyze_dynamics
from .muddiness import analyze_tonal_balance
from .transients import analyze_transients
from .musical import analyze_musicality
from .stereo import analyze_stereo
from .loudness import analyze_loudness
from .noise import analyze_noise_floor
from .reverb import estimate_reverb_tail
from .distortion import analyze_harmonic_distortion
from .reference import analyze_spectral_balance

logger = logging.getLogger("reasig.dsp")

# Target sample rate for consistent FFT bin sizes across all files
TARGET_SR = 44100
# Maximum duration to analyze (prevents OOM on long stems)
MAX_DURATION_SEC = 30.0


def analyze_audio_file(
    wav_path: str,
    user_question: str = "",
    stereo: bool = False,
    flags: AnalysisFlags | None = None,
) -> Dict[str, Any]:
    """
    Main entry point for DSP analysis of a single audio file.

    Args:
            from user_question via the keyword router.

    Returns:
        A combined dictionary of all analysis results.
    """
    logger.info("Starting DSP analysis for %s (stereo=%s)", wav_path, stereo)

    # Determine which modules to run
    if flags is None:
        flags = route_analysis(user_question)
        logger.debug("Router flags from prompt: %s", flags)

    try:
        # Load audio — stereo determines mono vs stereo loading
        if stereo:
            y_raw, sr_raw = librosa.load(
                wav_path,
                sr=TARGET_SR,
                mono=False,  # preserve stereo channels
                duration=MAX_DURATION_SEC,
            )
            sr = int(sr_raw)
            # Ensure we actually got a stereo file
            if y_raw.ndim == 1:
                # File was mono despite request — treat as mono
                logger.warning("Stereo requested but file %s is mono. Proceeding as mono.", wav_path)
                y_mono = y_raw
                y_stereo = None
            else:
                # Downmix to mono for all non-stereo modules
                y_mono = (y_raw[0] + y_raw[1]) / 2.0
                y_stereo = y_raw
        else:
            y_mono, sr_raw = librosa.load(
                wav_path,
                sr=TARGET_SR,
                mono=True,
                duration=MAX_DURATION_SEC,
            )
            sr = int(sr_raw)
            y_stereo = None

        if len(y_mono) == 0:
            raise ValueError(f"Audio file is empty or unreadable: {wav_path}")

        combined: Dict[str, Any] = {}

        # ── Spectrum (must run before muddiness and spectral balance) ─────────
        if flags.run_spectrum:
            spectrum_results = analyze_spectrum(y_mono, sr)
            combined.update(spectrum_results)

            # Spectral balance vs reference always runs with spectrum
            if "band_energy" in combined:
                combined.update(analyze_spectral_balance(combined["band_energy"]))

        # ── Dynamics + clipping (always bundled together) ─────────────────────
        if flags.run_dynamics:
            combined.update(analyze_dynamics(y_mono))

        # ── Tonal balance (muddiness / harshness / boxiness flags) ───────────
        if flags.run_muddiness:
            if flags.run_spectrum and "band_energy" in combined:
                combined["tonal_balance"] = analyze_tonal_balance(combined)
            else:
                # Spectrum wasn't run but muddiness was requested — run it now
                spectrum_for_muddiness = analyze_spectrum(y_mono, sr)
                combined["tonal_balance"] = analyze_tonal_balance(spectrum_for_muddiness)

        # ── Transients (onset detection + attack/decay timing) ────────────────
        if flags.run_transients:
            combined["transients"] = analyze_transients(y_mono, sr)

        # ── Musical (BPM + key via KK profiles) ──────────────────────────────
        if flags.run_musical:
            combined["musical"] = analyze_musicality(y_mono, sr)

        # ── Loudness (LUFS + per-platform deltas) ─────────────────────────────
        if flags.run_loudness:
            # Use stereo array for LUFS if available — more accurate ITU-R measurement
            y_for_lufs = y_stereo if y_stereo is not None else y_mono
            combined["loudness"] = analyze_loudness(y_for_lufs, sr)

        # ── Noise floor / SNR ─────────────────────────────────────────────────
        if flags.run_noise:
            combined["noise"] = analyze_noise_floor(y_mono, sr)

        # ── Reverb tail / RT60 ────────────────────────────────────────────────
        if flags.run_reverb:
            combined["reverb"] = estimate_reverb_tail(y_mono, sr)

        # ── Harmonic distortion (THD) ─────────────────────────────────────────
        if flags.run_distortion:
            combined["distortion"] = analyze_harmonic_distortion(y_mono, sr)

        # ── Stereo field (only if stereo mode requested and file is stereo) ───
        if stereo and y_stereo is not None:
            combined["stereo"] = analyze_stereo(y_stereo, sr)

        logger.info("Analysis complete for %s — %d top-level keys", wav_path, len(combined))
        return combined

    except Exception as e:
        logger.error("DSP analysis failed for %s: %s", wav_path, str(e))
        raise

